const typography = {
  useNextVariants: true,
  fontFamily: [
    'Nunito',
    'Prompt',
    'sans-serif',
    '-apple-system',
  ].join(','),
  fontSize: 16,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  h1: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 60,
    lineHeight: 1.25,
    letterSpacing: '-1.5px',
  },
  h2: {
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: 48,
    lineHeight: 1.3,
    letterSpacing: '-0.5px',
  },
  h3: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 40,
    lineHeight: 1.4,
  },
  h4: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 32,
    lineHeight: 1.5,
  },
  h5: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 24,
    lineHeight: 1.3,
    letterSpacing: 0.18,
    textTransform: 'capitalize',
  },
  h6: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 20,
    lineHeight: 1.2,
    letterSpacing: 0.15,
    textTransform: 'capitalize',
  },
  subtitle1: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 16,
    lineHeight: 1.5,
    letterSpacing: 0.15,
    textTransform: 'capitalize',
  },
  subtitle2: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 14,
    lineHeight: 1.5,
    letterSpacing: 0.1,
  },
  body1: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 1.5,
  },
  body2: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 14,
    lineHeight: 1.57,
    letterSpacing: 0.1,
  },
  button: {
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 14,
    lineHeight: 1.57,
    letterSpacing: 0.25,
    textTransform: 'uppercase',
  },
  caption: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 12,
    lineHeight: 1.33,
  },
  overline: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 10,
    lineHeight: 1.5,
  },
}

export default typography
